# duplication threshold [20 - 100]
MinLineCount: 20

# files/patterns to exclude
IgnorePatterns:
  - "**/test/**"
  - "**/tests/**"
  - "**/unittests/**"
  - "**/*.unittest*/**"
  - "**/spec/**"
  - "**/*.spec.*"
  - "**/__tests__/**"
  - "**/mocks/**"
  - "**/schema.*"
  - "**/migrations/**"
  - "**/migration/**"
  - "**/migrate/**"
  - "**/dist/**"
  
