# duplication threshold [10 - 100]
MinLineCount: 10

# files/patterns to exclude
IgnorePatterns:
  - coverage\**
  - scripts\**
  - node_modules\**
  - test\**
  - loaderio\**
  - .husky\**
  - *.json
